services:
  - type: web
    name: rpms-backend
    env: go
    rootDir: backend
    buildCommand: go build -o app main.go
    startCommand: ./app
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release
      - key: DEMO_MODE
        value: false
      - key: DB_HOST
        value: aws-1-eu-west-3.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: postgres.cnvqamvwynttfpslqrfv
      - key: DB_PASSWORD
        value: Yg@yoniti1011
      - key: DB_NAME
        value: postgres
      - key: DB_SSLMODE
        value: require
      - key: SUPABASE_URL
        value: https://cnvqamvwynttfpslqrfv.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNudnFhbXZ3eW50dGZwc2xxcmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2NzY3ODAsImV4cCI6MjA3OTI1Mjc4MH0.AV6XAy7WxU1AHWhai9GljMjxaWvZqezbVXvWEyhz9UE
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNudnFhbXZ3eW50dGZwc2xxcmZ2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzY3Njc4MCwiZXhwIjoyMDc5MjUyNzgwfQ.2f4ylSjwEagTL6MH2p1AS36HNjAY2eIl_V_v_drSbF4
      - key: JWT_SECRET
        value: 0493715adaf9304e8e0034c87965ddba04dbdae6dd1128e2d3c61dd489fb4df1
      - key: JWT_EXPIRY
        value: 24h
      - key: CORS_ORIGINS
        value: http://localhost:3000,http://localhost:3001
